### ISSUE TITLE
some setter for content-type

### ISSUE THREAD

**Issue by robertomurta** [RAvenGEr/simple-beast-client#3]
I could find no setter for content-type for post request, so  I hardcoded to sove my problem:	`m_request.set(http::field::content_type, "application/x-www-form-urlencoded");` at line 51 of client_private.hpp. and tried some implemetation of a setter (for future use) which I  didn't  tested:

at httpclient.hpp:
```
void setContentType(boost::string_view contentType = "application/x-www-form-urlencoded") {
     m_request.set(http::field::content_type, contentType);
}

```

**Comment by RAvenGEr** [comment]
Please see current version for a new POST API, which allows for content type to be set.
